name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 600453241670.dkr.ecr.us-east-1.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t your-repo-name .
          docker tag 600453241670.dkr.ecr.us-east-1.amazonaws.com/next-docker:latest
          docker push 600453241670.dkr.ecr.us-east-1.amazonaws.com/next-docker:latest