name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_REGISTRY_URL }}
        aws-region: us-east-1

    - name: Build and Push Docker image to ECR
      run: |
        docker build -t ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest .
        docker push ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest

    - name: Display ECR Docker image URI
      run: echo ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest
