name: Deploy to ECR and Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_REGISTRY_URL }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest .
        docker push ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # - name: Create Elastic Beanstalk application version
    #   run: |
    #     aws elasticbeanstalk create-application-version \
    #       --application-name your-application-name \
    #       --version-label your-version-label \
    #       --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=next-docker-bundle.zip

    # - name: Deploy to Elastic Beanstalk
    #   run: |
    #     aws elasticbeanstalk update-environment \
    #       --application-name your-application-name \
    #       --environment-name your-environment-name \
    #       --version-label your-version-label
