name: Docker Build and Push to ECR

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 600453241670.dkr.ecr.us-east-1.amazonaws.com/next-docker # Replace with your ECR registry URL
          region: us-east-1 # Replace with your AWS region

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 600453241670.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: next-docker # Replace with your ECR repository name
          TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
