name: Build and Deploy to ECR and Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Docker image
      run: docker build -t next-docker .

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_REGISTRY_URL }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Push Docker image to ECR
      run: |
        docker tag next-docker:latest ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest
        docker push ${{ secrets.AWS_REGISTRY_URL }}/next-docker:latest

    - name: Deploy to Elastic Beanstalk using AWS CodePipeline
      run: |
        aws elasticbeanstalk start-deployment \
          --application-name your-elasticbeanstalk-app \
          --environment-name your-elasticbeanstalk-env \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=next-docker-bundle.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}


