name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t ${{ secrets.AWS_ECR_REGISTRY_URI }}/next-docker:latest .

      - name: Login to AWS ECR
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_URI }}

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}/next-docker:latest

      # - name: Deploy to Beanstalk using CodePipeline
      #   run: |
      #     aws elasticbeanstalk create-application-version --application-name your-application-name \
      #       --version-label latest --source-bundle S3Bucket=${{ secrets.AWS_S3_BUCKET }},S3Key=latest.zip

      #     aws elasticbeanstalk update-environment --environment-name your-environment-name \
      #       --version-label latest

