name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-region>

      - name: Build and Push Docker Image
        run: |
          docker build -t 600453241670.dkr.ecr.us-east-1.amazonaws.com/next-docker:latest .
          docker push 600453241670.dkr.ecr.us-east-1.amazonaws.com/next-docker:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy Next-docker-test-env --staged